# Generated by Django 4.0.6 on 2023-02-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qiuz',
            new_name='Quiz',
        ),
    ]
