# Generated by Django 4.0.6 on 2023-02-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='content',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='price',
        ),
    ]
