# Generated by Django 4.0.6 on 2023-02-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_quiz_content_remove_quiz_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anwser',
            new_name='answer',
        ),
    ]
